### ISSUE TITLE
Motion Planning Problems

### ISSUE THREAD

**Issue by DoongLi** [MedlarTea/Mono-RPF#1]
Hi, thank you for your excellent work, I have a question：
In the whole process of  Peron Following, how to track people from the perspective of motion planning? Is there a waypoint?

**Comment by MedlarTea** [comment]
Yes, there is a waypoint which is (x-“distance”, 0) in the robot space considering the target person is on the position of (x,y)

**Comment by DoongLi** [comment]
From the current position of the robot to the Waypoint, whether there is an obstacle avoidance？ By the way, have you considered the situation of the waypoint is occupied and cannot be achieved？

**Comment by MedlarTea** [comment]
For the current system, yes, we do not consider the obstacle because our focus is the tracking part. But we have implemented a MPC for the obstacle avoidance in our laser-based RPF system. And in the future work we would add the motion planning module to this Mono-RPF system.



发自我的iPhone


------------------ Original ------------------
From: Dong Li ***@***.***&gt;
Date: Thu,Jul 6,2023 0:15 PM
To: MedlarTea/Mono-RPF ***@***.***&gt;
Cc: MedlarTea ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [MedlarTea/Mono-RPF] Motion Planning Problems (Issue #1)





 
From the current position of the robot to the Waypoint, whether there is an obstacle avoidance？ By the way, have you considered the situation of the waypoint is occupied and cannot be achieved？

**Comment by DoongLi** [comment]
Ok, thank you for your reply, have a great day!
